# CONFIGURATION OF DATABASE PATH:
DATABASE_PATH = "DB/bank.db"

# CONFIGURATION OF MAXIMUM OF TRANSACTION AND CLIENT MAXIMUM BALANCE CAN BE STORED:
MAX_BALANCE = 999_000_000_000_000
MAX_TRANSACTION = 100_000_000

# CONFIGURATION OF MAXIMUM USERNAME OF EACH ACCOUNT:
USERNAME_MAX_LENGTH = 16

# CONFIGURATION OF MAXIMUM AND MINUMUM PASSWORD OF EACH ACCOUNT:
PASSWORD_MIN_LENGTH = 15
PASSWORD_MAX_LENGTH = 128